[package]
name = "branchless_utf8"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
wide = "0.7.32"

[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "basic"
harness = false
